export type SpinnerProps = {}

export default function Spinner({}: SpinnerProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
      className="inline-block h-5 animate-spin"
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid"
      shapeRendering={'crispEdges'}
    >
      <circle
        cx="50"
        cy="50"
        fill="none"
        stroke="#cccccc"
        strokeWidth="11"
        r="30"
        strokeDasharray="120 40"
      ></circle>
    </svg>
  )
}

// <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" style="shape-rendering:crispedges;margin-right:-2px;display:block;background-repeat-y:initial;background-repeat-x:initial;background-color:rgb(255, 255, 255);animation-play-state:paused" ><circle cx="50" cy="50" fill="none" stroke="#e7e7e7" stroke-width="11" r="26" stroke-dasharray="122.52211349000194 42.840704496667314" transform="matrix(1,0,0,1,0,0)" style="transform:matrix(1, 0, 0, 1, 0, 0);animation-play-state:paused" ></circle><!-- generated by https://loading.io/ --></svg>
